# Generated by Django 6.0.7 on 2026-07-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('observaciones_cliente', models.TextField(blank=True)),
                ('respuesta_taller', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada'), ('ATENDIDA', 'Atendida'), ('NO_ASISTIO', 'No asistió')], default='SOLICITADA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api.cliente')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='api.servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='api.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_solicitada'],
            },
        ),
    ]
