# Generated by Django 6.0.7 on 2026-07-14 19:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_especialidad_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consecutivo de orden',
                'verbose_name_plural': 'Consecutivos de órdenes',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En revisión'), ('ESPERANDO_AUTORIZACION', 'Esperando autorización'), ('EN_REPARACION', 'En reparación'), ('EN_LAVADO', 'En lavado'), ('LISTO', 'Listo para retirar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=30)),
                ('motivo_ingreso', models.CharField(max_length=250)),
                ('observaciones_recepcion', models.TextField(blank=True)),
                ('kilometraje_ingreso', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_trabajo', to='api.cita')),
                ('empleado_recepciona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to='api.empleado')),
                ('empleado_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='api.empleado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='api.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
