# Generated by Django 6.0.7 on 2026-07-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_consecutivoorden_ordentrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En revisión'), ('ESPERANDO_AUTORIZACION', 'Esperando autorización'), ('EN_REPARACION', 'En reparación'), ('EN_LAVADO', 'En lavado'), ('LISTO', 'Listo para retirar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=30, null=True)),
                ('estado_nuevo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En revisión'), ('ESPERANDO_AUTORIZACION', 'Esperando autorización'), ('EN_REPARACION', 'En reparación'), ('EN_LAVADO', 'En lavado'), ('LISTO', 'Listo para retirar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('visible_cliente', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_realizados', to='api.empleado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='api.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Historial de estado de orden',
                'verbose_name_plural': 'Historiales de estados de órdenes',
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['orden', 'creado_en'], name='historial_orden_fecha_idx')],
            },
        ),
    ]
