# Generated by Django 6.0.7 on 2026-07-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historialestadoorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(choices=[('INFORMATIVO', 'Informativo'), ('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('URGENTE', 'Urgente')], default='INFORMATIVO', max_length=20)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('estado_respuesta', models.CharField(choices=[('NO_REQUERIDA', 'No requerida'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='NO_REQUERIDA', max_length=20)),
                ('comentario_cliente', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('visible_cliente', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_realizados', to='api.empleado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='api.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['orden', 'estado_respuesta'], name='diag_orden_respuesta_idx')],
            },
        ),
    ]
