# Generated by Django 6.0.7 on 2026-07-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_detalleservicioorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_recomendada', models.DateField(blank=True, null=True)),
                ('kilometraje_recomendado', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('visible_cliente', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_creadas', to='api.empleado')),
                ('orden_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_mantenimiento', to='api.ordentrabajo')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_mantenimiento', to='api.servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_mantenimiento', to='api.vehiculo')),
            ],
            options={
                'verbose_name': 'Recomendación de mantenimiento',
                'verbose_name_plural': 'Recomendaciones de mantenimiento',
                'ordering': ['estado', 'fecha_recomendada', 'kilometraje_recomendado'],
                'indexes': [models.Index(fields=['vehiculo', 'estado'], name='recomend_vehiculo_estado_idx')],
            },
        ),
    ]
